# Describes the services for the Simple Timer integration
start_timer:
  name: Start Timer
  description: Starts a countdown timer for the device. The associated switch is turned on.
  fields:
    entry_id:
      name: Entry ID
      description: The config entry ID of the simple timer sensor.
      required: true
      selector:
        text:
    duration:
      name: Duration
      description: The duration of the timer in minutes.
      required: true
      selector:
        number:
          min: 1
          max: 1000
          unit_of_measurement: "minutes"

cancel_timer:
  name: Cancel Timer
  description: Cancels an active countdown timer.
  fields:
    entry_id:
      name: Entry ID
      description: The config entry ID of the simple timer sensor.
      required: true
      selector:
        text:

update_switch_entity:
  name: Update Switch Entity
  description: Tells the sensor which switch entity to monitor for runtime calculation.
  fields:
    entry_id:
      name: Entry ID
      description: The config entry ID of the simple timer sensor.
      required: true
      selector:
        text:
    switch_entity_id:
      name: Switch Entity
      description: The entity ID of the switch to monitor (e.g., switch.my_timer).
      required: true
      selector:
        entity:
          domain: switch

force_name_sync:
  name: Force Name Sync
  description: Forces immediate synchronization of sensor names after entry rename.
  fields:
    entry_id:
      name: Entry ID (Optional)
      description: The config entry ID to sync. If omitted, syncs all Simple Timer sensors.
      required: false
      selector:
        text:

manual_power_toggle:
  name: Manual Power Toggle
  description: Manually toggles switch power and sends appropriate notifications.
  fields:
    entry_id:
      name: Entry ID
      description: The config entry ID of the simple timer sensor.
      required: true
      selector:
        text:
    action:
      name: Action
      description: The action to perform (turn_on or turn_off).
      required: true
      selector:
        select:
          options:
            - turn_on
            - turn_off